name: minisauras

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: minisauras
      uses: TeamTigers/minisauras@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.MINISAURUS_MINIFY_JS_CSS }}
      id: dir
      with:
        directory: 'minify-trial/' ## minify all files under assets directory
